/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Interface.SortListener;
import java.awt.Color;
import java.awt.Graphics;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import sortcomparator.ObservableArray;

/**
 *
 * @author Mathieu
 */
public class sortView extends javax.swing.JPanel implements SortListener{

    /**
     * Creates new form sortView
     */
    public sortView() 
    {
        initComponents();
    }
    
     ObservableArray _tab;
     
    @Override
    public void paint(Graphics g)
    {
        super.paintComponent(g);
        System.out.println("Refresh");
        if(_tab != null)
        {
            for(int index = 0; index < _tab.length ; index++)
            {
                g.setColor(_tab.getColor(index));
                g.fillRect(index*(_barWidth+1), this.getHeight(), _barWidth, (int) -((_tab.Tab[index]/_maxValue)*this.getHeight()));
            }
        }
    }
    
    private double _maxValue;
    private int _barWidth;
    
    public void initSortVisual(double maxValue, int nbElements)
    {
        _maxValue = maxValue;
        _barWidth = ((this.getWidth()-nbElements)/(nbElements));
    }
    
    @Override
    public void SetObservableArray(ObservableArray tab, Double maxValue) 
    {
        _tab = tab;
        initSortVisual(maxValue, _tab.length);
        System.out.println("SetObservable");
        this.repaint();
    }

    @Override
    public void UpdateArray() {
        System.out.println("UpdateArray");
        this.paintImmediately(0,0, this.getWidth(), this.getHeight());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables




}
